---
- name: Install Packages
  hosts: DEV_SERVER
  tasks:
    - name: "Setting up repository"
      ansible.builtin.yum:
        name: http://repo.mysql.com/mysql-community-release-el7-7.noarch.rpm
        disable_gpg_check: true
        update_cache: true
        state: present

    - name: Install MySQL Server and python
      ansible.builtin.yum:
        update_cache: true
        name: 
          - mysql-server
          #- MySQL-python
        state: present

    - name: start and enable mysql service
      ansible.builtin.service:
        name: mysqld
        state: started
        enabled: yes
